(function(h,m,y){function w(a){return(Math.exp(a)+Math.exp(-a))/2}function x(a){return(Math.exp(a)-Math.exp(-a))/2}function z(a,c){a.save();a.strokeStyle=A;a.fillStyle=A;a.translate(10+c,0);a.beginPath();a.moveTo(-10,0);a.lineTo(0,8);a.lineTo(0,-8);a.fill();a.lineWidth=5;a.beginPath();m.segment(a,[0,-15],[0,21]);a.stroke();a.lineWidth=2;a.beginPath();for(var b=-15;15>=b;b+=7.5)m.segment(a,[0,b],[11.25,b+7.5]);a.stroke();a.restore()}function B(a,c,b,g){var d=c.weight/(2*c.tension),e=c.tension/c.linMass,
t=e*Math.log(d+Math.sqrt(1+d*d)),C=e*w(t/e),d=e*w((c.valleySize/2+t)/e)-C,l=[[0,d],[b/c.meterScale,0]],n=e*x(t/e),n=2*(e*x((c.valleySize/2+t)/e)-n);a.save();a.fillStyle=E;if(!g){a.strokeStyle=F;a.beginPath();m.segment(a,h.mul2(c.meterScale,l[0]),h.mul2(c.meterScale,l[1]));m.segment(a,[0,0],h.mul2(c.meterScale,l[0]));a.stroke();if(0<p){var u=c.altitude-f[p][1]-d;a.fillText(NLS.get("Valley distance")+": "+Math.round(10*u)/10+" m",10,c.meterScale*(d+u/2))}a.textAlign="center";a.fillText(NLS.get("Vertical distance")+
": "+Math.round(10*d)/10+" m",0,-5);a.textAlign="end";a.fillText(NLS.get("Cable length")+": "+Math.round(10*n)/10+" m",b-5,-5);a.textAlign="start"}a.strokeStyle=I;var n=-1,v;a.beginPath();a.moveTo(0,c.meterScale*d);for(var u=c.valleySize/2/50,k=1;50>=k;k++){var q=e*w((k*u+t)/e)-C,q=d-q,q=[k*u,q];a.lineTo(c.meterScale*q[0],c.meterScale*q[1]);var r=h.proj2(q,l),s=h.sqDist2(r,q);s>n&&(n=s,v=[q,r])}a.stroke();g||(a.strokeStyle=F,a.beginPath(),m.segment(a,h.mul2(c.meterScale,v[0]),h.mul2(c.meterScale,
v[1])),a.stroke(),n=Math.sqrt(n),a.fillText(NLS.get("Chord distance")+": "+Math.round(10*n)/10+"m",c.meterScale*v[0][0],c.meterScale*v[0][1]+20),g=c.tension*x((c.valleySize/2+t)/e),g=Math.sqrt(g*g+c.tension*c.tension),a.fillText(NLS.get("Tension")+": "+Math.round(10*g)/10+" kg",5-b,-5),a.fillStyle=J,a.fillRect(-5,c.meterScale*d-5,10,30));a.restore()}function k(){var a=$("#schema")[0],c=$("div.slider,input[type=checkbox]").getUIData();c.linMass/=1E3;c.altitude<r+20&&(c.altitude=r+20);c.altitude>s&&
(c.altitude=s);if(0<f.length){for(var b=c.altitude,g=[],d,e=p;0<e;e--)if(d=f[e][1]-f[e-1][1],d=(f[e][1]-b)/d,0<=d&&1>=d){g.push(f[e][0]+d*(f[e-1][0]-f[e][0]));break}for(e=p;e<f.length;e++)if(d=f[e][1]-f[e-1][1],d=(f[e][1]-b)/d,0<=d&&1>=d){g.push(f[e][0]+d*(f[e-1][0]-f[e][0]));break}c.anchors=2>g.length?[f[0][0],f[f.length-1][0]]:g;c.valleySize=c.anchors[1]-c.anchors[0]}else c.altitude=0;b=a.getContext("2d");g=a.width/2-25;c.meterScale=g/(c.valleySize/2);b.save();b.font="16px Arial";$("body").css("background-color");
b.fillStyle="rgb(10,20,40)";b.fillRect(0,0,a.width,a.height);b.translate(a.width/2,25);if(!(2>f.length)){e=c.meterScale;b.save();b.fillStyle=K;b.scale(1,-1);b.translate(-c.anchors[0]*e-g,-c.altitude*e);b.beginPath();b.moveTo(e*f[0][0],0);for(d=0;d<f.length;d++)b.lineTo(e*f[d][0],e*f[d][1]);b.lineTo(e*f[f.length-1][0],0);b.fill();"C8"==$("#profile").val()&&(d=[-216,2090],b.translate(e*d[0],e*d[1]),b.scale(0.75,-0.75),b.drawImage(l,-l.width/2,-l.height/2));b.restore()}b.strokeStyle=L;b.fillStyle=E;
b.lineWidth=1;e=[50,100,200,500,1E3,2E3];b.beginPath();m.segment(b,[-g,0],[g,0]);for(var k in e){d=e[k];var h=c.meterScale*d;40<h&&h<a.height-60&&(m.segment(b,[-g,h],[g,h]),b.fillText("-"+d.toString()+" m",-g,h-4))}b.stroke();b.save();b.scale(-1,1);z(b,g);B(b,c,g,!0);b.restore();z(b,g);B(b,c,g,!1);a=a.height-35;b.fillText(NLS.get("Anchors distance")+": "+Math.round(10*c.valleySize)/10+" m",40-g,a-8);b.beginPath();m.arrowHead(b,[5-g,a],[g-5,a],10);m.arrowHead(b,[g-5,a],[5-g,a],10);b.moveTo(g-5,a);
b.lineTo(5-g,a);b.stroke();b.restore()}function H(){var a=$("#profile").val(),c=y[a],a=y.presets[a];if(void 0===c)f=[],p=-1,r=500,s=5E3;else{f=h.cspline(c,0.5,8);for(var b=0,g=f[0][1],d=1;d<f.length;d++)f[d][1]<g&&(b=d,g=f[d][1]);p=b;r=f[p][1];b=f[0][1];g=f[f.length-1][1];for(d=0;d<p;d++)f[d][1]>b&&(b=f[d][1]);for(d=p;d<f.length;d++)f[d][1]>g&&(g=f[d][1]);s=Math.min(b,g)}if(void 0!==a){$("#weight").val(30);$("#linMass").val(30);for(var e in a)$("#"+e).val(a[e])}void 0===c?($("#altitude").fancySlider("visibility",
!1),$("#valleySize").fancySlider("visibility",!0)):($("#altitude").fancySlider("visibility",!0),$("#valleySize").fancySlider("visibility",!1));k()}var E="#80E0E0",L="#606060",K="#302010",A="#909090",F="#C0C020",I="#FFFF00",J="#80FF80",l=new Image;l.src="img/C8icon.png";l.onload=function(){k()};var f,p,r,s;$("document").ready(function(){$("#schema").icanvas();$.finalizeUI();$("#profile").change(H);$("div.slider").on("slidechange",k);$("div.slider").on("change",k);H()})})(G,D,profiles);
