(function(h,m,I){function A(a){return(Math.exp(a)+Math.exp(-a))/2}function B(a){return(Math.exp(a)-Math.exp(-a))/2}function J(a,b){a.save();a.strokeStyle=n;a.fillStyle=n;a.translate(10+b,0);a.beginPath();a.moveTo(-10,0);a.lineTo(0,8);a.lineTo(0,-8);a.fill();a.lineWidth=5;a.beginPath();m.segment(a,[0,-15],[0,21]);a.stroke();a.lineWidth=2;a.beginPath();for(var c=-15;15>=c;c+=7.5)m.segment(a,[0,c],[11.25,c+7.5]);a.stroke();a.restore()}function K(a,b,c,g){var d=b.weight/(2*b.tension),e=b.tension/b.linMass,
w=e*Math.log(d+Math.sqrt(1+d*d)),t=e*A(w/e),d=e*A((b.valleySize/2+w)/e)-t,k=[[0,d],[c/b.meterScale,0]],p=e*B(w/e),p=2*(e*B((b.valleySize/2+w)/e)-p);a.save();a.fillStyle=y;b.forSnapshot&&(a.lineWidth=3);if(!g){a.strokeStyle=z;a.beginPath();m.segment(a,h.mul2(b.meterScale,k[0]),h.mul2(b.meterScale,k[1]));m.segment(a,[0,0],h.mul2(b.meterScale,k[0]));a.stroke();if(0<q){var n=b.altitude-f[q][1]-d;a.fillText(NLS.get("Valley distance")+": "+Math.round(10*n)/10+" m",20,b.meterScale*(d+n/2))}a.textAlign="center";
a.fillText(NLS.get("Vertical distance")+": "+Math.round(10*d)/10+" m",0,-8);a.textAlign="end";a.fillText(NLS.get("Cable length")+": "+Math.round(10*p)/10+" m",c-5,-8);a.textAlign="start";n=2*Math.sqrt(b.valleySize*b.valleySize/4+d*d)}a.strokeStyle=C;var p=-1,u;a.beginPath();a.moveTo(0,b.meterScale*d);for(var l=b.valleySize/2/50,s=1;50>=s;s++){var r=e*A((s*l+w)/e)-t,r=d-r,r=[s*l,r];a.lineTo(b.meterScale*r[0],b.meterScale*r[1]);var v=h.proj2(r,k),x=h.sqDist2(v,r);x>p&&(p=x,u=[r,v])}a.stroke();g||(a.strokeStyle=
z,a.beginPath(),m.segment(a,h.mul2(b.meterScale,u[0]),h.mul2(b.meterScale,u[1])),a.stroke(),p=Math.sqrt(p),a.fillText(NLS.get("Chord distance")+": "+Math.round(10*p)/10+"m",b.meterScale*u[0][0],b.meterScale*u[0][1]+25),a.fillText(NLS.get("Straight distance")+": "+Math.round(1*n)/1+"m",b.meterScale*u[0][0],b.meterScale*u[0][1]+50),g=b.tension*B((b.valleySize/2+w)/e),g=Math.sqrt(g*g+b.tension*b.tension),a.fillText(NLS.get("Tension")+": "+Math.round(10*g)/10+" kg",5-c,-8),"C8"===$("#profile").val()&&
(a.beginPath(),a.moveTo(0,b.meterScale*d),a.lineTo(-25,b.meterScale*(d+101)),a.lineTo(25,b.meterScale*(d+101)),a.lineTo(0,b.meterScale*d),a.stroke(),a.fillText("Effective mirror area: D=50m",35,b.meterScale*(d+101))),a.fillStyle=E,a.fillRect(-5,b.meterScale*d-5,10,30));a.restore()}function l(){var a=$("#schema")[0],b=$("div.slider,input[type=checkbox]").getUIData();b.linMass/=1E3;b.altitude<s+20&&(b.altitude=s+20);b.altitude>v&&(b.altitude=v);if(0<f.length){var c=b.altitude,g=[],d,e;for(e=q;0<e;e--)if(d=
f[e][1]-f[e-1][1],d=(f[e][1]-c)/d,0<=d&&1>=d){g.push(f[e][0]+d*(f[e-1][0]-f[e][0]));break}for(e=q;e<f.length;e++)if(d=f[e][1]-f[e-1][1],d=(f[e][1]-c)/d,0<=d&&1>=d){g.push(f[e][0]+d*(f[e-1][0]-f[e][0]));break}b.anchors=2>g.length?[f[0][0],f[f.length-1][0]]:g;b.valleySize=b.anchors[1]-b.anchors[0]}else b.altitude=0;c=a.getContext("2d");g=a.width/2-25;b.meterScale=g/(b.valleySize/2);b.forSnapshot?(x="#E0FFFF",F="#FFC060",y="#040810",H="#404040",n="#505050",z="#8080FF",C="#1010C0",E="#106010"):(x="#081020",
F="#302010",y="#80E0E0",H="#606060",n="#909090",z="#C0C020",C="#FFFF00",E="#80FF80");c.save();c.font=b.forSnapshot?"bold 24px Calibri":"16px Arial";c.fillStyle=x;c.fillRect(0,0,a.width,a.height);c.translate(a.width/2,50);if(!(2>f.length)){e=b.meterScale;c.save();c.fillStyle=F;c.scale(1,-1);c.translate(-b.anchors[0]*e-g,-b.altitude*e);c.beginPath();c.moveTo(e*f[0][0],0);for(d=0;d<f.length;d++)c.lineTo(e*f[d][0],e*f[d][1]);c.lineTo(e*f[f.length-1][0],0);c.fill();"C8"===$("#profile").val()&&(d=[-216,
2090],c.translate(e*d[0],e*d[1]),b.forSnapshot||(c.scale(0.75,-0.75),c.drawImage(t,-t.width/2,-t.height/2)));c.restore()}c.strokeStyle=H;c.fillStyle=y;c.lineWidth=1;e=[50,100,200,500,1E3,2E3];d=40;b.forSnapshot&&(d=100);c.beginPath();m.segment(c,[-g,0],[g,0]);for(var h in e){var l=e[h],k=b.meterScale*l;k>d&&k<a.height-60&&(m.segment(c,[-g,k],[g,k]),c.fillText("-"+l.toString()+" m",-g,k-4))}c.stroke();c.save();c.scale(-1,1);J(c,g);K(c,b,g,!0);c.restore();J(c,g);K(c,b,g,!1);a=a.height-50-15;c.fillText(NLS.get("Anchors distance")+
": "+Math.round(10*b.valleySize)/10+" m",40-g,a-8);c.beginPath();m.arrowHead(c,[5-g,a],[g-5,a],10);m.arrowHead(c,[g-5,a],[5-g,a],10);c.moveTo(g-5,a);c.lineTo(5-g,a);c.stroke();c.restore()}function L(){var a=$("#profile").val(),b=I[a],a=I.presets[a];if(void 0===b)f=[],q=-1,s=500,v=5E3;else{f=h.cspline(b,0.5,8);for(var c=0,g=f[0][1],d=1;d<f.length;d++)f[d][1]<g&&(c=d,g=f[d][1]);q=c;s=f[q][1];c=f[0][1];g=f[f.length-1][1];for(d=0;d<q;d++)f[d][1]>c&&(c=f[d][1]);for(d=q;d<f.length;d++)f[d][1]>g&&(g=f[d][1]);
v=Math.min(c,g)}if(void 0!==a){$("#weight").val(30);$("#linMass").val(30);for(var e in a)$("#"+e).val(a[e])}void 0===b?($("#altitude").fancySlider("visibility",!1),$("#valleySize").fancySlider("visibility",!0)):($("#altitude").fancySlider("visibility",!0),$("#valleySize").fancySlider("visibility",!1));l()}var x,F,y,H,n,z,C,E,f,q,s,v,t=new Image;t.src="img/C8icon.png";t.onload=function(){l()};$("document").ready(function(){$("#schema").icanvas();$.finalizeUI();$("#profile").change(L);$("div.slider").on("change slidechange",
l);$("#forSnapshot").on("change keyup",l);L()})})(G,D,profiles);
