(function(c,w,F){function x(){var d=c("#drawPresets").getBool(),a=c("#mapzoomlayer")[0],b=a.getContext("2d"),g=a.width,a=a.height,f=g/2,e=a/2;b.save();b.scale(1,-1);b.translate(0,-a);b.clearRect(0,0,g,a);b.strokeStyle="#081020";b.fillStyle="#C0E0FF";b.fillRect(f-2,0,4,e-40);b.fillRect(f-2,e+40,4,e-40);b.fillRect(0,e-2,f-40,4);b.fillRect(f+40,e-2,f-40,4);b.beginPath();b.moveTo(f,0);b.lineTo(f,e-20);b.moveTo(f,e+20);b.lineTo(f,a);b.moveTo(0,e);b.lineTo(f-20,e);b.moveTo(f+20,e);b.lineTo(g,e);b.stroke();
if(d){b.save();b.scale(1,-1);b.translate(0,-a);b.strokeStyle="#FFFF40";d=s/(n-1);g=c("#posX").val();f=c("#posY").val();f=[(g-l[0])/d,(f-l[1])/d];g=p/2-f[0];f=p/2-f[1];for(e=0;e<h.length;e++){var k=[(h[e].pos[0]-l[0])/d+g,a-1-((h[e].pos[1]-l[1])/d+f)];w.target(b,k[0],k[1],y)}b.restore()}b.restore()}function z(){var d=c("#drawPresets").getBool(),a=c("#maplayer")[0],b=a.getContext("2d"),g=a.width,f=a.height,e=s/(q-1),k=c("#posX").val(),m=c("#posY").val(),a=[(k-l[0])/e,(m-l[1])/e];b.save();b.scale(1,
-1);b.translate(0,-f);b.clearRect(0,0,g,f);b.strokeStyle="#C0D0E0";b.beginPath();b.moveTo(a[0],0);b.lineTo(a[0],f);b.moveTo(0,a[1]);b.lineTo(g,a[1]);b.stroke();b.strokeRect(a[0]-r/2,a[1]-r/2,r,r);if(d){b.strokeStyle="#FFFF40";for(d=0;d<h.length;d++)a=[(h[d].pos[0]-l[0])/e,(h[d].pos[1]-l[1])/e],w.target(b,a[0],a[1],y)}b.restore();e=s/(n-1);a=[(k-l[0])/e,n-1-(m-l[1])/e];b=String(1+p/2-a[0]);a=String(1+p/2-a[1]);c("#mapzoom").css({left:b+"px",top:a+"px"});x()}function A(){var d=c("#coord").val().replace(/[;,\s]+/g,
"|").split("|");""===d[0]&&d.shift();var a=parseFloat(d[0]),b=parseFloat(d[1]),d=parseFloat(d[2]);isNaN(d)&&(d=2E3);return"LLA"===c("#from-unit").val()?[b,a,d]:[a,b,d]}function t(){var d=c("#from-unit").val(),a=A(),b=new CoordConvert,g=a[0],f=a[1],a=a[2],e,h,m,l;if(!isNaN(g)&&!isNaN(f)&&!isNaN(a)){switch(d){case "UVA":e=[g,f,a];break;case "LLA":m=[g,f,a];e=b.LLAtoUVA(g,f,a);break;case "ENA":l=[g,f,a];e=b.ENAtoUVA(g,f,a);break;case "XYZ":h=[g,f,a],e=b.XYZtoUVA(g,f,a)}void 0===m&&(m=b.UVAtoLLA(e[0],
e[1],e[2]));void 0===l&&(l=b.UVAtoENA(e[0],e[1],e[2]));void 0===h&&(h=b.UVAtoXYZ(e[0],e[1],e[2]));"pos"!==k&&(d=c("#posX"),g=e[0],d.val()!==g&&d.val(g),d=c("#posY"),g=e[1],d.val()!==g&&d.val(g));c("#UVA0").text(e[0].toFixed(3));c("#UVA1").text(e[1].toFixed(3));c("#UVA2").text(e[2].toFixed(3));c("#LLA1").html(m[1].toFixed(8)+"°");c("#LLA0").html(m[0].toFixed(8)+"°");c("#LLA2").text(m[2].toFixed(3));c("#LLA1b").html(b.dms(m[1]));c("#LLA0b").html(b.dms(m[0]));c("#ENA0").text(l[0].toFixed(3));c("#ENA1").text(l[1].toFixed(3));
c("#ENA2").text(l[2].toFixed(3));c("#XYZ0").text(h[0].toFixed(3));c("#XYZ1").text(h[1].toFixed(3));c("#XYZ2").text(h[2].toFixed(3));b.accurate(e)?(c(".res").css({"background-color":"",color:""}),c("#warning").hide()):(c(".res").css({"background-color":"#A01020",color:"white"}),c("#warning").show())}else c(".res").text(""),c(".res").css({"background-color":"",color:""}),c("#warning").hide();z()}function B(){if("UVA"===c("#from-unit").val())for(var d=A(),a=0;a<h.length;a++)if(F.eq3(h[a].pos,d)){c("#presets").val(h[a].name);
return}c("#presets").val("-")}function H(){void 0===k&&(k="pos");if("coord"!==k){var d=new CoordConvert,a=[0,0,0];a[0]=parseFloat(c("#posX").val());a[1]=parseFloat(c("#posY").val());a[2]=parseFloat(c("#UVA2").text());isNaN(a[2])&&(a[2]=2063.144);var b,g=[3,3,3];switch(c("#from-unit").val()){case "UVA":b=a;break;case "LLA":b=d.UVAtoLLA(a[0],a[1],a[2]);b=[b[1],b[0],b[2]];g=[8,8,3];break;case "ENA":b=d.UVAtoENA(a[0],a[1],a[2]);break;case "XYZ":b=d.UVAtoXYZ(a[0],a[1],a[2])}b=[b[0].toFixed(g[0]),b[1].toFixed(g[1]),
b[2].toFixed(g[2])];c("#coord").val(b.join(" "));B();t()}"pos"===k&&(k=void 0)}function C(){void 0===k&&(k="coord");B();t();"coord"===k&&(k=void 0)}function E(){for(var d=c("#presets").val(),a=0;a<h.length;a++)if(h[a].name===d){k="coord";c("#coord").val(h[a].posAsString);c("#from-unit").val("UVA");t();k=void 0;break}}function I(){var d=c("#from-unit").val(),a=["#"+d+"0","#"+d+"1","#"+d+"2"];"LLA"===d&&(a=[a[1],a[0],a[2]]);d=[c(a[0]).text(),c(a[1]).text(),c(a[2]).text()];c("#coord").val(d.join(" ").replace(/°/g,
""));C()}var q=512,n=4096,l=[-800,-600],p=512,s=1E3,r=q/(n/q),h=[],u;for(u in Coord.presets){var v=Coord.presets[u];h.push(c.extend(!0,{posAsString:[v.pos[0].toFixed(3),v.pos[1].toFixed(3),v.pos[2].toFixed(3)].join(" ")},Coord.presets[u]))}var y=10,k;c("document").ready(function(){for(var d=c("#presets"),a=0;a<h.length;a++){var b=h[a].name;d.append("<option value='"+b+"'>"+b+"</option>")}c("#presets").val(h[0].name);c.finalizeUI();c("#coord").on("change keyup",C);c("#from-unit").on("change",I);c("#presets").on("change keyup",
E);c("div.slider").on("change slidechange",H);c("#drawPresets").on("change keyup",z);a=d=p;c("#maplayer").attr({width:a,height:d});c("#mapzoomlayer").attr({width:a,height:d});d=c("#maplayer").icanvas();d=new VirtualTanslate(d,c("#posX"),c("#posY"));d.option("yUp",!0);d=c("#mapzoomlayer").icanvas();d=new VirtualTanslate(d,c("#posX"),c("#posY"));d.option("yUp",!0);d.option("dragBackground",!0);d.option("xScale",n/q);d.option("yScale",n/q);E();x()})})(jQuery,D,G);
