(function(a,x,K){function r(a,c,g,k,f,b,l,h){for(var e=0;e<a.length;e++){var m=[(a[e][0]-c[0])/g+f,(a[e][1]-c[1])/g+b];0<k&&(m[1]=k-1-m[1]);x.target(h,m[0],m[1],l)}}function q(){var d=a("#drawPresets").getBool(),c=a("#draw2010").getBool(),g=a("#draw2012").getBool(),k=a("#draw2013").getBool(),f=a("#maplayer")[0],b=f.getContext("2d"),l=f.width,h=f.height,e=y/(t-1),n=a("#posX").val(),q=a("#posY").val(),f=[(n-m[0])/e,(q-m[1])/e];b.save();b.scale(1,-1);b.translate(0,-h);b.clearRect(0,0,l,h);b.strokeStyle=
"#C0D0E0";b.beginPath();b.moveTo(f[0],0);b.lineTo(f[0],h);b.moveTo(0,f[1]);b.lineTo(l,f[1]);b.stroke();b.strokeRect(f[0]-w/2,f[1]-w/2,w,w);if(d){b.strokeStyle="#FFFF40";for(d=0;d<p.length;d++)f=[(p[d].pos[0]-m[0])/e,(p[d].pos[1]-m[1])/e],x.target(b,f[0],f[1],u)}c&&(b.strokeStyle="#40FFFF",r(measures2010,m,e,0,0,0,z,b));g&&(b.strokeStyle="#FFFFFF",r(sol2012,m,e,0,0,0,z,b));k&&(b.strokeStyle="#FF4040",r(sol2013,m,e,0,0,0,z,b));b.restore();e=y/(s-1);f=[(n-m[0])/e,s-1-(q-m[1])/e];c=String(1+v/2-f[0]);
g=String(1+v/2-f[1]);a("#mapzoom").css({left:c+"px",top:g+"px"});E()}function E(){var d=a("#drawPresets").getBool(),c=a("#draw2010").getBool(),g=a("#draw2012").getBool(),k=a("#draw2013").getBool(),f=a("#mapzoomlayer")[0],b=f.getContext("2d"),l=f.width,f=f.height,h=l/2,e=f/2;b.save();b.scale(1,-1);b.translate(0,-f);b.clearRect(0,0,l,f);b.strokeStyle="#081020";b.fillStyle="#C0E0FF";b.fillRect(h-2,0,4,e-40);b.fillRect(h-2,e+40,4,e-40);b.fillRect(0,e-2,h-40,4);b.fillRect(h+40,e-2,h-40,4);b.beginPath();
b.moveTo(h,0);b.lineTo(h,e-20);b.moveTo(h,e+20);b.lineTo(h,f);b.moveTo(0,e);b.lineTo(h-20,e);b.moveTo(h+20,e);b.lineTo(l,e);b.stroke();if(d||k||g||c){b.save();b.scale(1,-1);b.translate(0,-f);l=y/(s-1);h=a("#posX").val();e=a("#posY").val();e=[(h-m[0])/l,(e-m[1])/l];h=v/2-e[0];e=v/2-e[1];if(d){b.strokeStyle="#FFFF40";for(d=0;d<p.length;d++){var n=[(p[d].pos[0]-m[0])/l+h,f-1-((p[d].pos[1]-m[1])/l+e)];x.target(b,n[0],n[1],u)}}c&&(b.strokeStyle="#40FFFF",r(measures2010,m,l,f,h,e,u,b));g&&(b.strokeStyle=
"#FFFFFF",r(sol2012,m,l,f,h,e,u,b));k&&(b.strokeStyle="#FF4040",r(sol2013,m,l,f,h,e,u,b));b.restore()}b.restore()}function F(){var d=a("#coord").val().replace(/[;,\s]+/g,"|").split("|");""===d[0]&&d.shift();var c=parseFloat(d[0]),g=parseFloat(d[1]),d=parseFloat(d[2]);isNaN(d)&&(d=2E3);return"LLA"===a("#from-unit").val()?[g,c,d]:[c,g,d]}function A(){var d=a("#from-unit").val(),c=F(),g=new CoordConvert,k=c[0],f=c[1],c=c[2],b,l,h,e;if(!isNaN(k)&&!isNaN(f)&&!isNaN(c)){switch(d){case "UVA":b=[k,f,c];break;
case "LLA":h=[k,f,c];b=g.LLAtoUVA(k,f,c);break;case "ENA":e=[k,f,c];b=g.ENAtoUVA(k,f,c);break;case "XYZ":l=[k,f,c],b=g.XYZtoUVA(k,f,c)}void 0===h&&(h=g.UVAtoLLA(b[0],b[1],b[2]));void 0===e&&(e=g.UVAtoENA(b[0],b[1],b[2]));void 0===l&&(l=g.UVAtoXYZ(b[0],b[1],b[2]));"pos"!==n&&(d=a("#posX"),k=b[0],d.val()!==k&&d.val(k),d=a("#posY"),k=b[1],d.val()!==k&&d.val(k));a("#UVA0").text(b[0].toFixed(3));a("#UVA1").text(b[1].toFixed(3));a("#UVA2").text(b[2].toFixed(3));a("#LLA1").html(h[1].toFixed(8)+"°");a("#LLA0").html(h[0].toFixed(8)+
"°");a("#LLA2").text(h[2].toFixed(3));a("#LLA1b").html(g.dms(h[1]));a("#LLA0b").html(g.dms(h[0]));a("#ENA0").text(e[0].toFixed(3));a("#ENA1").text(e[1].toFixed(3));a("#ENA2").text(e[2].toFixed(3));a("#XYZ0").text(l[0].toFixed(3));a("#XYZ1").text(l[1].toFixed(3));a("#XYZ2").text(l[2].toFixed(3));g.accurate(b)?(a(".res").css({"background-color":"",color:""}),a("#warning").hide()):(a(".res").css({"background-color":"#A01020",color:"white"}),a("#warning").show())}else a(".res").text(""),a(".res").css({"background-color":"",
color:""}),a("#warning").hide();q()}function H(){if("UVA"===a("#from-unit").val())for(var d=F(),c=0;c<p.length;c++)if(K.eq3(p[c].pos,d)){a("#presets").val(p[c].name);return}a("#presets").val("-")}function L(){void 0===n&&(n="pos");if("coord"!==n){var d=new CoordConvert,c=[0,0,0];c[0]=parseFloat(a("#posX").val());c[1]=parseFloat(a("#posY").val());c[2]=parseFloat(a("#UVA2").text());isNaN(c[2])&&(c[2]=2063.144);var g,k=[3,3,3];switch(a("#from-unit").val()){case "UVA":g=c;break;case "LLA":g=d.UVAtoLLA(c[0],
c[1],c[2]);g=[g[1],g[0],g[2]];k=[8,8,3];break;case "ENA":g=d.UVAtoENA(c[0],c[1],c[2]);break;case "XYZ":g=d.UVAtoXYZ(c[0],c[1],c[2])}g=[g[0].toFixed(k[0]),g[1].toFixed(k[1]),g[2].toFixed(k[2])];a("#coord").val(g.join(" "));H();A()}"pos"===n&&(n=void 0)}function I(){void 0===n&&(n="coord");H();A();"coord"===n&&(n=void 0)}function J(){for(var d=a("#presets").val(),c=0;c<p.length;c++)if(p[c].name===d){n="coord";a("#coord").val(p[c].posAsString);a("#from-unit").val("UVA");A();n=void 0;break}}function M(){var d=
a("#from-unit").val(),c=["#"+d+"0","#"+d+"1","#"+d+"2"];"LLA"===d&&(c=[c[1],c[0],c[2]]);d=[a(c[0]).text(),a(c[1]).text(),a(c[2]).text()];a("#coord").val(d.join(" ").replace(/°/g,""));I()}var t=512,s=4096,m=[-800,-600],v=512,y=1E3,w=t/(s/t),p=[],B;for(B in Coord.presets){var C=Coord.presets[B];p.push(a.extend(!0,{posAsString:[C.pos[0].toFixed(3),C.pos[1].toFixed(3),C.pos[2].toFixed(3)].join(" ")},Coord.presets[B]))}var u=10,z=5,n;a("document").ready(function(){for(var d=a("#presets"),c=0;c<p.length;c++){var g=
p[c].name;d.append("<option value='"+g+"'>"+g+"</option>")}a("#presets").val(p[0].name);a.finalizeUI();a("#coord").on("change keyup",I);a("#from-unit").on("change",M);a("#presets").on("change keyup",J);a("div.slider").on("change slidechange",L);a("#drawPresets").on("change keyup",q);a("#draw2010").on("change keyup",q);a("#draw2012").on("change keyup",q);a("#draw2013").on("change keyup",q);c=d=v;a("#maplayer").attr({width:c,height:d});a("#mapzoomlayer").attr({width:c,height:d});d=a("#maplayer").icanvas();
d=new VirtualTanslate(d,a("#posX"),a("#posY"));d.option("yUp",!0);d=a("#mapzoomlayer").icanvas();d=new VirtualTanslate(d,a("#posX"),a("#posY"));d.option("yUp",!0);d.option("dragBackground",!0);d.option("xScale",s/t);d.option("yScale",s/t);J();E()})})(jQuery,D,G);
