(function(C,K,y){function s(a,b){return[(a[0]-p[0])/O,(a[1]-p[1])/O,(a[0]-p[0])/z+b.coordOffsetX,(a[1]-p[1])/z+b.coordOffsetY]}function L(a,b,d,c){var e=[Math.floor(a[0]),Math.floor(a[1])];a=[a[0]-e[0],a[1]-e[1]];if(0>e[0]||0>e[1]||e[0]>=d||e[1]>=c)return-1;c=e[0]+e[1]*d;e=(1-a[1])*((1-a[0])*b[c]+a[0]*b[c+1]);c+=d;return e+=a[1]*((1-a[0])*b[c]+a[0]*b[c+1])}function P(){for(var a=$("input").getUIData(),a=[a.UVA0,a.UVA1,a.UVA2],b=t.length;b--;)y.sqDist2(a,t[b])<W&&t.splice(b,1);t.push(a);A()}function X(){var a=
JSON.stringify(t);console.log(a)}function Q(){for(var a=$("div.slider,input").getUIData(),b=["posX","posY","radius","groundRadius","zOffset"],d=0;d<b.length;d++)a[b[d]]=R[b[d]];b=[(a.posX-p[0])/z,(a.posY-p[1])/z];a.imgOffsetX=E/2-b[0]+Number(B);a.imgOffsetY=E/2-(M-1-b[1])+0*B;a.coordOffsetX=E/2-b[0]+0.5*B;a.coordOffsetY=E/2-b[1]+0.5*B;a.center=s([a.posX,a.posY],a);a.centerZ=a.zOffset+L(a.center,C.data,F,F);a.radius2=a.radius*a.radius;a.groundRadius2=a.groundRadius*a.groundRadius;return a}function A(){if(!H){var a=
$("#mapzoomlayertop")[0],b=Q(),d=a.getContext("2d"),c=a.width,e=a.height,a=s([b.UVA0,b.UVA1],b),f=L(a,C.data,c,e),f=l(f),f={probe2010:[b.UVA0,b.UVA1,f],probe:[b.UVA0,b.UVA1,b.UVA2],MirN:I.MirN.pos,MirS:I.MirS.pos};$("#C1-U").text(String(l(b.posX)));$("#C1-V").text(String(l(b.posY)));$("#C1-A").text(String(l(b.centerZ+b.radius)));var m=b.radius*b.radius,g;for(g in f){$("#"+g+"-Z").text(String(f[g][2]));var h=y.sqDist2(f[g],[b.posX,b.posY]);if(h<=m){var h=b.centerZ+b.radius-Math.sqrt(m-h),q=l(h);$("#"+
g+"-sphZ").text(String(q));$("#"+g+"-diff").text(String(l(h-f[g][2])))}else $("#"+g+"-sphZ").text("N/A"),$("#"+g+"-diff").text("N/A")}d.save();d.clearRect(0,0,c,e);d.scale(1,-1);d.translate(0,-e);d.strokeStyle="#FF2020";D.cross(d,[a[2],a[3]],c,e);c=s([b.UVAb0,b.UVAb1],b);d.beginPath();d.moveTo(c[2]-v,c[3]);d.lineTo(c[2]+v,c[3]);d.moveTo(c[2],c[3]-v);d.lineTo(c[2],c[3]+v);d.stroke();d.save();void 0!==d.setLineDash?d.setLineDash([10,5]):void 0!==d.mozDash&&(d.mozDash=[10,5]);d.beginPath();d.moveTo(a[2],
a[3]);d.lineTo(c[2],c[3]);d.stroke();d.restore();d.strokeStyle="#F0B0E0";b.drawC1&&(c=s([b.posX,b.posY],b),D.target(d,c[2],c[3],10));b.drawMirN&&(c=s(I.MirN.pos,b),D.target(d,c[2],c[3],10));b.drawMirS&&(c=s(I.MirS.pos,b),D.target(d,c[2],c[3],10));if(b.drawIGN){d.strokeStyle="#B0E0B0";for(a=0;a<measures2010.length;a++)c=s(measures2010[a],b),D.target(d,c[2],c[3],10)}if(b.drawProbes){d.strokeStyle="#B0D0E0";for(a=0;a<t.length;a++)c=s(t[a],b),D.target(d,c[2],c[3],10)}d.restore();d=[$("#UVA0").val(),$("#UVA1").val(),
$("#UVA2").val()];c=[$("#UVAb0").val(),$("#UVAb1").val(),$("#UVAb2").val()];b=y.dist2(d,c);d=y.dist3(d,c);$("#distance2").text(String(l(b))+"m (horiz)");$("#distance3").text(String(l(d))+"m (3D)")}}function S(){if(!H){H=!0;var a=$("#mapzoomlayer")[0],b=Q();$("#mapzoom").css({left:String(b.imgOffsetX)+"px",top:String(b.imgOffsetY)+"px"});var d=[b.center[2],b.center[3]],c=z,e=[b.coordOffsetX,b.coordOffsetY],f=B,m=a.getContext("2d"),g=a.width,a=a.height;m.save();m.clearRect(0,0,g,a);for(var h=m.createImageData(g,
a),q,k,n,l=b.groundRadius/c,s=l*l,t=255*b.transp2,u=1/b.allowedH,p=0;p<a;p++)for(var r=0;r<g;r++)if(1===f?(q=r+p*g,n=C.data[q]):n=L([(r-e[0])/f,(p-e[1])/f],C.data,g,a),q=4*(r+(a-p-1)*g),k=y.sqDist2([r,p],d),h.data[q+0]=0,h.data[q+1]=0,h.data[q+2]=0,h.data[q+3]=0,k<s&&(k=b.radius-Math.sqrt(b.radius2-c*c*k),k=b.centerZ+k-n,k*=u,1>Math.abs(k))){a:{var w=(k+1)/2;if(w>=x[0][0])for(k=1;k<x.length;k++)if(w<x[k][0]){n=x[k-1];k=x[k];var w=(w-n[0])/(k[0]-n[0]),v=1-w;n=[v*n[1][0]+w*k[1][0],v*n[1][1]+w*k[1][1],
v*n[1][2]+w*k[1][2]];break a}n=[0,0,0]}h.data[q+0]=n[0];h.data[q+1]=n[1];h.data[q+2]=n[2];h.data[q+3]=t}m.putImageData(h,0,0);m.strokeStyle="#E0E060";D.target(m,d[0],a-1-d[1],l,0.8);l>T/c&&D.target(m,d[0],a-1-d[1]-T/c,l/2,0.8);m.restore();$("#tele-scale-min").text(-Math.round(10*b.allowedH)/10);$("#tele-scale-max").text(Math.round(10*b.allowedH)/10);H=!1;A()}}function Y(){$(".scale").each(function(){var a=$(this),b=parseFloat(a.css("height")),d=parseFloat(a.css("width"))-100,c=parseFloat(a.attr("min")),
e=parseFloat(a.attr("max"));a.css("position","relative");var f=$(this).getId(),m=f+"-background",g=f+"-ticks";a.append('<table class="layout"><tr><td id="'+(f+"-min")+'">'+c+'</td><td><div style="position:relative; height:'+b+"px; width:"+d+"px; \" ><canvas id='"+m+"' style='z-index=1'></canvas><canvas id='"+g+"' style='z-index=2'></canvas></div><td id=\""+(f+"-max")+'">'+e+"</td></tr></table>");f=$("#"+m);f.css("position","absolute");f.height(b);f.width(d);$.drawTicksInCanvas(f,c,e);f=f[0].getContext("2d");
a=$.parseJSON("["+a.attr("data")+"]");f.save();for(var m=f.createLinearGradient(0,0,d,0),h=0;h<a.length-1;h+=2)m.addColorStop(a[h],a[h+1]);f.fillStyle=m;f.fillRect(0,0,d,b);f.restore();g=$("#"+g);g.css("position","absolute");g.height(b);g.width(d);$.drawTicksInCanvas(g,c,e)})}function Z(a){if("keydown"===a.type){var b=$("#zOffset"),d=b.getFloat(),c=0.1;a.shiftKey&&(c*=5);a.ctrlKey&&(c*=2);switch(a.which){case 90:b.val(d-c);break;case 88:b.val(d+c);break;case 83:P()}}return!0}function l(a){return Math.round(1E3*
a)/1E3}function U(a){return[l(a[0]),l(a[1]),l(a[2])]}function u(a,b,d){var c="UVA",e="ENA";void 0!==a&&(c+=a,e+=a);a=[$("#"+c+"0").val(),$("#"+c+"1").val(),$("#"+c+"2").val()];void 0!==b&&(a[b]=d);b=U(V.UVAtoENA(a));N=!0;$("#"+e+"0").val(b[0]);$("#"+e+"1").val(b[1]);$("#"+e+"2").val(b[2]);N=!1;A()}function r(a,b,d){var c="ENA",e="UVA";void 0!==a&&(c+=a,e+=a);N||(a=[$("#"+c+"0").val(),$("#"+c+"1").val(),$("#"+c+"2").val()],void 0!==b&&(a[b]=d),b=U(V.ENAtoUVA(a)),$("#"+e+"0").val(b[0]),$("#"+e+"1").val(b[1]),
$("#"+e+"2").val(b[2]))}var V=new CoordConvert,t=[];void 0!==measures2013&&(t=measures2013);for(var W=0.1*0.1,v=16,R,J=0;J<K.length;J++)"North Mirror"===K[J].name&&(R=K[J].data);var F=512,M=4096,p=[-800,-600],E=512,T=202*Math.sin(Math.PI/180*(6+-28/60+-1.02975/3600));Math.sin(Math.PI/180*(-0.95+-48.94955/3600));var O=1E3/F,z=1E3/M,B=M/F,I=Coord.presets,x,H=!1,N=!1;$("document").ready(function(){var a=$.parseJSON("["+$("#tele-scale").attr("data")+"]"),b;x=[];for(b=0;b<a.length-1;b+=2){var d=parseInt(a[b+
1].substring(1,3),16),c=parseInt(a[b+1].substring(3,5),16),e=parseInt(a[b+1].substring(5,7),16);x.push([a[b],[d,c,e]])}$.finalizeUI();Y();a=Coord.presets.MirS.pos;$("#UVA0").val(a[0]);$("#UVA1").val(a[1]);$("#UVA2").val(a[2]);u();$("#UVAb0").val(a[0]);$("#UVAb1").val(a[1]);$("#UVAb2").val(a[2]);u("b");var f=[{sel:"#UVA0",pos:0,suffix:"",cb:u},{sel:"#UVA1",pos:1,suffix:"",cb:u},{sel:"#UVA2",pos:2,suffix:"",cb:u},{sel:"#ENA0",pos:0,suffix:"",cb:r},{sel:"#ENA1",pos:1,suffix:"",cb:r},{sel:"#ENA2",pos:2,
suffix:"",cb:r},{sel:"#UVAb0",pos:0,suffix:"b",cb:u},{sel:"#UVAb1",pos:1,suffix:"b",cb:u},{sel:"#UVAb2",pos:2,suffix:"b",cb:u},{sel:"#ENAb0",pos:0,suffix:"b",cb:r},{sel:"#ENAb1",pos:1,suffix:"b",cb:r},{sel:"#ENAb2",pos:2,suffix:"b",cb:r}];for(b=0;b<f.length;b++)(function(){var a=f[b];$(a.sel).on("change",function(){a.cb(a.suffix)});$(a.sel).on("spin",function(b,c){a.cb(a.suffix,a.pos,c.value)})})();parseInt($("#ground-scale-min").text(),10);parseInt($("#ground-scale-max").text(),10);$("div.slider").on("change slidechange",
S);$(".JQspinner").on("change spinchange",A);$("input.boolean").on("change",A);$("#mapzoomlayer").attr({width:heightmap.sizeX,height:heightmap.sizeY});$("#mapzoomlayertop").attr({width:heightmap.sizeX,height:heightmap.sizeY});$("#mapzoomlayertop").icanvas().on("keydown",Z);a=$("#mapzoomlayertop").icanvas();d=new VirtualTanslate(a,$("#UVAb0"),$("#UVAb1"));d.option("sensorSize",2*v);d.option("yUp",!0);d=new VirtualTanslate(a,$("#UVA0"),$("#UVA1"));d.option("yUp",!0);$("#SaveProbe").click(P);$("#DumpProbes").click(X);
S()})})(heightmap,spherepreset,G);
