(function(B,H,s){function u(a,d){return[(a[0]-n[0])/v,(a[1]-n[1])/v,(a[0]-n[0])/x+d.coordOffsetX,(a[1]-n[1])/x+d.coordOffsetY]}function C(a,d,b,c){var f=[Math.floor(a[0]),Math.floor(a[1])];a=[a[0]-f[0],a[1]-f[1]];if(0>f[0]||0>f[1]||f[0]>=b||f[1]>=c)return-1;c=f[0]+f[1]*b;f=(1-a[1])*((1-a[0])*d[c]+a[0]*d[c+1]);c+=b;return f+=a[1]*((1-a[0])*d[c]+a[0]*d[c+1])}function K(a,d,b,c,f,e){var l=a.getContext("2d"),g=a.width;a=a.height;l.save();l.clearRect(0,0,g,a);for(var h=l.createImageData(g,a),m,k,p,q=255/
(L-I),n=b.groundRadius/c,t=n*n,v=255*b.transp,w=255*b.transp2,x=1/b.allowedH,z=0;z<a;z++)for(var A=0;A<g;A++){1===e?(m=A+z*g,p=B.data[m]):p=C([(A-f[0])/e,(z-f[1])/e],B.data,g,a);m=4*(A+(a-z-1)*g);k=s.sqDist2([A,z],d);var r=(p-I)*q;0<=r&&256>r?(h.data[m+0]=64,h.data[m+1]=255-r,h.data[m+2]=255,h.data[m+3]=v):(h.data[m+0]=0,h.data[m+1]=0,h.data[m+2]=0,h.data[m+3]=0);if(k<t&&(k=b.radius-Math.sqrt(b.radius2-c*c*k),k=b.centerZ+k-p,k*=x,1>Math.abs(k))){a:{r=(k+1)/2;if(r>=y[0][0])for(k=1;k<y.length;k++)if(r<
y[k][0]){p=y[k-1];k=y[k];var r=(r-p[0])/(k[0]-p[0]),u=1-r;p=[u*p[1][0]+r*k[1][0],u*p[1][1]+r*k[1][1],u*p[1][2]+r*k[1][2]];break a}p=[0,0,0]}h.data[m+0]=p[0];h.data[m+1]=p[1];h.data[m+2]=p[2];h.data[m+3]=w}}l.putImageData(h,0,0);l.strokeStyle="#E0E060";D.target(l,d[0],a-1-d[1],n,0.8);n>M/c&&D.target(l,d[0],a-1-d[1]-M/c,n/2,0.8);l.restore()}function N(){var a=parseFloat($("#presets").val()),a=H[a].data,d;for(d in a)$("#"+d).val(a[d])}function O(){if($("#alignC8").getBool()){var a=q.C8.pos[0];$("#posX").setValueIfDiff(a);
var d=$("#posY").getFloat(),b=P[2]*((d-q.C8.pos[1])/P[1]),a=C([(a-n[0])/v,(d-n[1])/v],B.data,heightmap.sizeX,heightmap.sizeY),d=$("#radius").val(),b=q.C8.pos[2]+(b-d)-a;$("#zOffset").setValueIfDiff(b)}b=$("div.slider,input[type=checkbox]").getUIData();a=[(b.posX-n[0])/x,(b.posY-n[1])/x];b.imgOffsetX=E/2-a[0]+Number(t);b.imgOffsetY=E/2-(J-1-a[1])+0*t;b.coordOffsetX=E/2-a[0]+0.5*t;b.coordOffsetY=E/2-a[1]+0.5*t;b.center=u([b.posX,b.posY],b);b.centerZ=b.zOffset+C(b.center,B.data,F,F);b.radius2=b.radius*
b.radius;b.groundRadius2=b.groundRadius*b.groundRadius;return b}function Q(){if(!w){w=!0;var a=$("#map")[0],d=$("#mapzoomlayer")[0],b=$("#mapzoomlayertop")[0],c=O();K(a,c.center,c,v,[0,0],1);$("#mapzoom").css({left:String(c.imgOffsetX)+"px",top:String(c.imgOffsetY)+"px"});c.transp=0;K(d,[c.center[2],c.center[3]],c,x,[c.coordOffsetX,c.coordOffsetY],t);var a=b.getContext("2d"),d=b.width,b=b.height,f=u([c.cursX,c.cursY],c),e=C(f,B.data,d,b),e=Math.floor(0.5+1E3*e)/1E3,e={probe:[c.cursX,c.cursY,e],MirN:q.MirN.pos,
MirS:q.MirS.pos};$("#C1-U").text(String(Math.floor(0.5+1E3*c.posX)/1E3));$("#C1-V").text(String(Math.floor(0.5+1E3*c.posY)/1E3));$("#C1-A").text(String(Math.floor(0.5+1E3*(c.centerZ+c.radius))/1E3));var l=c.radius*c.radius,g;for(g in e){$("#"+g+"-Z").text(String(e[g][2]));var h=s.sqDist2(e[g],[c.posX,c.posY]);if(h<=l){var h=c.centerZ+c.radius-Math.sqrt(l-h),m=Math.floor(0.5+1E3*h)/1E3;$("#"+g+"-sphZ").text(String(m));$("#"+g+"-diff").text(String(Math.floor(0.5+1E3*(h-e[g][2]))/1E3))}else $("#"+g+
"-sphZ").text("N/A"),$("#"+g+"-diff").text("N/A")}a.save();a.clearRect(0,0,d,b);a.scale(1,-1);a.translate(0,-b);a.strokeStyle="#E0D0B0";D.cross(a,[f[2],f[3]],d,b);c.drawMirN&&(g=u(q.MirN.pos,c),D.target(a,g[2],g[3],10));c.drawMirS&&(g=u(q.MirS.pos,c),D.target(a,g[2],g[3],10));a.restore();$("#tele-scale-min").text(-Math.round(10*c.allowedH)/10);$("#tele-scale-max").text(Math.round(10*c.allowedH)/10);w=!1}}function R(){if(!w){w=!0;var a=$("#maplayer")[0],d=O(),b=a.getContext("2d"),c=a.width,a=a.height,
f=1/v,e=s.mul2(-f,n),l=s.add2(s.mul2(f,q.C1.pos),e),g=s.add2(s.mul2(f,q.C8.pos),e),h=s.add2(s.mul2(f,q.MirN.pos),e),f=s.add2(s.mul2(f,q.MirS.pos),e);b.save();b.scale(1,-1);b.translate(0,-a);b.clearRect(0,0,c,a);d.drawIGN1&&(b.strokeStyle="#C0D0E0",D.cross(b,e,c,a));d.drawC1&&(b.strokeStyle="#E0C0D0",D.cross(b,l,c,a));d.drawC8&&(b.strokeStyle="#E0C0D0",D.cross(b,g,c,a));d.drawMirN&&(b.strokeStyle="#E0C0D0",D.cross(b,h,c,a));d.drawMirS&&(b.strokeStyle="#E0C0D0",D.cross(b,f,c,a));b.restore();w=!1}}function T(){$(".scale").each(function(){var a=
$(this),d=parseFloat(a.css("height")),b=parseFloat(a.css("width"))-100,c=parseFloat(a.attr("min")),f=parseFloat(a.attr("max"));a.css("position","relative");var e=$(this).getId(),l=e+"-background",g=e+"-ticks";a.append('<table class="layout"><tr><td id="'+(e+"-min")+'">'+c+'</td><td><div style="position:relative; height:'+d+"px; width:"+b+"px; \" ><canvas id='"+l+"' style='z-index=1'></canvas><canvas id='"+g+"' style='z-index=2'></canvas></div><td id=\""+(e+"-max")+'">'+f+"</td></tr></table>");e=$("#"+
l);e.css("position","absolute");e.height(d);e.width(b);$.drawTicksInCanvas(e,c,f);e=e[0].getContext("2d");a=$.parseJSON("["+a.attr("data")+"]");e.save();for(var l=e.createLinearGradient(0,0,b,0),h=0;h<a.length-1;h+=2)l.addColorStop(a[h],a[h+1]);e.fillStyle=l;e.fillRect(0,0,b,d);e.restore();g=$("#"+g);g.css("position","absolute");g.height(d);g.width(b);$.drawTicksInCanvas(g,c,f)})}function S(a){if("keydown"===a.type){var d=$("#zOffset"),b=d.getFloat(),c=0.1;a.shiftKey&&(c*=5);a.ctrlKey&&(c*=2);switch(a.which){case 90:d.val(b-
c);break;case 88:d.val(b+c);break;case 83:"mapzoomlayertop"===a.srcElement.id?(a=$("div.slider,input[type=checkbox]").getUIData(),a=JSON.stringify({pos:[a.cursX,a.cursY]})):(a=$("div.slider,input[type=checkbox]").getUIData(),a=JSON.stringify(a)),console.log(a)}}return!0}var F=512,J=4096,n=[-800,-600],I=0,L=0,E=512,M=202*Math.sin(Math.PI/180*(6+-28/60+-1.02975/3600));Math.sin(Math.PI/180*(-0.95+-48.94955/3600));var v=1E3/F,x=1E3/J,t=J/F,P=[0,0.715318,0.6993],q=Coord.presets,y,w=!1;$("document").ready(function(){var a=
$.parseJSON("["+$("#tele-scale").attr("data")+"]"),d;y=[];for(d=0;d<a.length-1;d+=2){var b=parseInt(a[d+1].substring(1,3),16),c=parseInt(a[d+1].substring(3,5),16),f=parseInt(a[d+1].substring(5,7),16);y.push([a[d],[b,c,f]])}a=$("#presets");for(d=0;d<H.length;d++)a.append('<option value="'+String(d)+'">'+H[d].name+"</option>");a.on("change",N);$.finalizeUI();T();N();I=parseInt($("#ground-scale-min").text(),10);L=parseInt($("#ground-scale-max").text(),10);$("input").on("change",R);$("#res").val("PAL");
$("div.slider").on("change slidechange",Q);$("#map").attr({width:heightmap.sizeX,height:heightmap.sizeY});$("#maplayer").attr({width:heightmap.sizeX,height:heightmap.sizeY});$("#mapzoomlayer").attr({width:heightmap.sizeX,height:heightmap.sizeY});$("#mapzoomlayertop").attr({width:heightmap.sizeX,height:heightmap.sizeY});d=$("#maplayer").icanvas();a=new VirtualTanslate(d,$("#posX"),$("#posY"));a.option("yUp",!0);d.on("keydown",S);$("#mapzoomlayertop").icanvas().on("keydown",S);d=$("#mapzoomlayertop").icanvas();
a=new VirtualTanslate(d,$("#cursX"),$("#cursY"));a.option("yUp",!0);a.option("xScale",t);a.option("yScale",t);R();Q()})})(heightmap,spherepreset,G);
